//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIF.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIF.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The matrix is the incorrect size..
        /// </summary>
        internal static string ArgumentBadSize {
            get {
                return ResourceManager.GetString("ArgumentBadSize", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The column length must be greater than zero..
        /// </summary>
        internal static string ArgumentColumnLength {
            get {
                return ResourceManager.GetString("ArgumentColumnLength", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The column specified is invalid..
        /// </summary>
        internal static string ArgumentInvalidColumn {
            get {
                return ResourceManager.GetString("ArgumentInvalidColumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The row specified is invalid..
        /// </summary>
        internal static string ArgumentInvalidRow {
            get {
                return ResourceManager.GetString("ArgumentInvalidRow", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The specified matrices are incompatible for this operation..
        /// </summary>
        internal static string ArgumentMatricesIncompatible {
            get {
                return ResourceManager.GetString("ArgumentMatricesIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Thie matrix is not a column vector..
        /// </summary>
        internal static string ArgumentMatrixisNotColumnVector {
            get {
                return ResourceManager.GetString("ArgumentMatrixisNotColumnVector", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Thie matrix is not a row vector..
        /// </summary>
        internal static string ArgumentMatrixisNotRowVector {
            get {
                return ResourceManager.GetString("ArgumentMatrixisNotRowVector", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Thie matrix is not a vector..
        /// </summary>
        internal static string ArgumentMatrixIsNotVector {
            get {
                return ResourceManager.GetString("ArgumentMatrixIsNotVector", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The row length must be greater than zero..
        /// </summary>
        internal static string ArgumentRowLength {
            get {
                return ResourceManager.GetString("ArgumentRowLength", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The specified size must be greater than zero..
        /// </summary>
        internal static string ArgumentSizeZero {
            get {
                return ResourceManager.GetString("ArgumentSizeZero", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The start column must be less than the end column..
        /// </summary>
        internal static string ArgumentStartColumnGreaterThanEndRow {
            get {
                return ResourceManager.GetString("ArgumentStartColumnGreaterThanEndRow", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The start row must be less than the end row..
        /// </summary>
        internal static string ArgumentStartRowGreaterThanEndRow {
            get {
                return ResourceManager.GetString("ArgumentStartRowGreaterThanEndRow", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The vector supplied does not match the row and column count..
        /// </summary>
        internal static string ArgumentVectorNotValid {
            get {
                return ResourceManager.GetString("ArgumentVectorNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The network has not been trained..
        /// </summary>
        internal static string NetworkNotTrained {
            get {
                return ResourceManager.GetString("NetworkNotTrained", resourceCulture);
            }
        }
    }
}
